---
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - check
  - test

variables:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  paths:
    - .m2/repository

sast:
  stage: check

secret_detection:
  stage: check

OSV scanner:
  image:
    name: golang:latest
  stage: check
  before_script:
    - "go install github.com/google/osv-scanner/cmd/osv-scanner@v1"
  script:
    - 'PATH="${PATH}:$(go env GOPATH)/bin" osv-scanner -r .'
  timeout: 10 minutes

super linter:
  image:
    name: ghcr.io/super-linter/super-linter:latest
    entrypoint:
      - ""
  stage: check
  variables:
    RUN_LOCAL: "true"
    DEFAULT_BRANCH: "main"
    VALIDATE_ALL_CODEBASE: "true"
    LINTER_RULES_PATH: "."
    FILTER_REGEX_EXCLUDE: "(gradlew|gradlew.bat|gradle/*|mvnw|mvnw.cmd|.m2/*|.mvn/**)"
  before_script:
    - 'ln -s "$(pwd)" /tmp/lint'
  script:
    - "/action/lib/linter.sh"
  timeout: 10 minutes

versions:
  image:
    name: leplusorg/maven-check-versions:1.0.0@sha256:e8f760bb1faf3d3c333d75810e82289fdd275688421cc8bad04cdbbc757ae5a5
  script:
    - "/opt/maven-check-versions.sh"
  stage: check
  timeout: 10 minutes

verify:openjdk17:
  stage: test
  image: maven:3-openjdk-17-slim
  script:
    - "./mvnw $MAVEN_CLI_OPTS verify"
  only:
    - master
