---

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

stages:
  - check
  - test

variables:
  MAVEN_OPTS: >
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=true
    -DdeployAtEnd=true

cache:
  paths:
    - .m2/repository

sast:
  stage: check

secret_detection:
  stage: check

super linter:
  image:
    name: github/super-linter:latest
    entrypoint:
      - ''
  stage: check
  variables:
    RUN_LOCAL: 'true'
    VALIDATE_ALL_CODEBASE: 'true'
    FILTER_REGEX_EXCLUDE: '(.aws/*|gradlew|gradlew.bat|gradle/*|mvnw|mvnw.cmd|.mvn/*)'
  before_script:
    - 'ln -s "$(pwd)" /tmp/lint'
  script:
    - '/action/lib/linter.sh'
  timeout: 10 minutes

versions:
  image:
    name: leplusorg/maven-check-versions:latest
  script:
    - '/opt/maven-check-versions.sh'
  stage: check
  timeout: 10 minutes

verify:openjdk17:
  stage: test
  image: maven:3-openjdk-17-slim
  script:
    - './mvnw $MAVEN_CLI_OPTS verify'
  only:
    - master
